### ISSUE TITLE
Provide a way to specify a path to the toggle endpoint

### ISSUE THREAD

**Issue by php-coder** [marceloverdijk/togglz-spring-boot#2]
As user I don't want to use default path (`/togglz`). Could you provide a way to configure it in my `application.yml`?

**Comment by marceloverdijk** [comment]
The toggle endpoint path can be changed by setting the `togglz.endpoint.id` application property.
Let me know if that's sufficient so I can close the issue.

**Comment by php-coder** [comment]
Ah, ok, then.
