### ISSUE TITLE
No qualifying bean of type org.togglz.core.spi.FeatureProvider when trying to use togglz.feature-enums

### ISSUE THREAD

**Issue by php-coder** [marceloverdijk/togglz-spring-boot#5]
I'm trying to use this module but it fails with:

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.togglz.spring.boot.autoconfigure.TogglzAutoConfiguration$FeatureManagerConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.togglz.core.spi.FeatureProvider org.togglz.spring.boot.autoconfigure.TogglzAutoConfiguration$FeatureManagerConfiguration.featureProvider; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.togglz.core.spi.FeatureProvider] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
```

- The full log available here: https://travis-ci.org/php-coder/mystamps/jobs/104494693
- `application.properties`: https://github.com/php-coder/mystamps/blob/togglz_boot/src/main/resources/application.properties#L32
- Configuration: https://github.com/php-coder/mystamps/blob/togglz_boot/src/main/java/ru/mystamps/web/support/togglz/TogglzConfig.java
- Source of the project: https://github.com/php-coder/mystamps/tree/togglz_boot

Could you take a look at it, please? I'm suspecting that the problem in ordering, so just in case I'm using JDK 1.8.0_45

**Comment by marceloverdijk** [comment]
I just cloned https://github.com/php-coder/mystamps/tree/togglz_boot and I could run the app successfully using mvn spring-boot:run

The Java version I have is 1.8.0_60.

Is it only failing on Travis or also locally?
Are you sure the latest `togglz-spring-boot-starter` is installed in your local /travis repo? The `togglz.feature-enums` application property was only added recently so maybe the `togglz-spring-boot-starter` jar is out of date?

You can check of the `togglz-spring-boot-starter` jar contains a `TogglzAutoConfiguration` that class has this auto configuration:
```
    @Configuration
    @ConditionalOnMissingBean(FeatureProvider.class)
    @ConditionalOnProperty(name = "togglz.feature-enums")
    protected static class FeatureProviderConfiguration {

        @Autowired
        private TogglzProperties properties;

        @Bean
        public FeatureProvider featureProvider() {
            return new EnumBasedFeatureProvider(properties.getFeatureEnums());
        }
    }
```

**Comment by marceloverdijk** [comment]
@php-coder are you still facing the issue?

**Comment by php-coder** [comment]
I didn't look at it.

**Comment by marceloverdijk** [comment]
@php-coder ok, when you have time let me know how it goes. I had one other test user which was able to use the starter successfully.

**Comment by marceloverdijk** [comment]
I found the issue in your app and created a PR to fix it: https://github.com/php-coder/mystamps/pull/338

**Comment by php-coder** [comment]
As far I understand my problem was because of outdated version, right?

**Comment by marceloverdijk** [comment]
@php-coder was related to wrong dep and after that because the endpoint was enabled explicitly without having boot actuator dep..
